Jwt_Template/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Jwt_Template.Areas.HelpPage.ModelDescriptions;
using Jwt_Template.Areas.HelpPage.Models;

namespace Jwt_Template.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Jwt_Template/Controllers/FillDocxController.cs
using Jwt_Template.Filters;
using Jwt_Template.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Jwt_Template.Controllers
{
    public class FillDocxController : Controller
    {
        private string CurrentDirectory = $"{AppDomain.CurrentDomain.BaseDirectory}";
        // GET: FillDocx
        public ActionResult Index(tblFileDetails model)
        {
            using (DB_Entities context = new DB_Entities())
            {
                var allFiles = (from r in context.tblFileDetails select r).ToList();
                if (allFiles != null)
                {
                    model.FileList = allFiles;
                    return View(model);
                }  
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Generate(string nameTemplate, HttpPostedFileBase jsonName)
        {
            string ext = Path.GetExtension(jsonName.FileName);
            if (ext == ".json")
            {
                var timeStamp = InfoVuln.GetInstance().TimeStamp;
                if (!Directory.Exists(Server.MapPath($"~/UploadedFiles/Json/{timeStamp}")))
                    Directory.CreateDirectory(Server.MapPath($"~/UploadedFiles/Json/{timeStamp}"));

                string path = Path.Combine(Server.MapPath($"~/UploadedFiles/Json/{timeStamp}"), jsonName.FileName);

                jsonName.SaveAs(path);

                //Create token to authorize
                Session["Token"] = JwtManager.GenerateToken(new Random().Next(100).ToString());

                var parameters = new Dictionary<string, string> { { "NameTemplate", nameTemplate }, { "Jsonpath", path } };
                var encodedContent = new FormUrlEncodedContent(parameters);

                HttpResponseMessage response =
                    await RequestHelper.PostRequestWithToken($"api/FillDocx/Fill", Session["Token"].ToString(), encodedContent);

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string filename = await response.Content.ReadAsStringAsync();
                    if(filename == "null")
                    {
                        TempData["msg"] = "<script>alert('Json format or template format error, please reformat your file again!!!');</script>";
                        return RedirectToAction("Index");
                    }
                        
                    filename = filename.Replace("\\","").Replace("\"","");
                    Session["filename"] = filename;

                    return RedirectToAction("Download", new { filename = filename });
                }     
            }

            TempData["msg"] = "<script>alert('Upload file error or Not exist template!!!');</script>";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Download()
        {
            if (Session["filename"] == null)
            {
                TempData["msg"] = "<script>alert('File Download not exist!!!');</script>";
                return RedirectToAction("Index");
            }

            string fileName = Session["filename"].ToString();
            Session.Remove("filename");

            var filepath = $"{CurrentDirectory}Renders/{fileName}";

            var memory = new MemoryStream();
            using (var stream = new FileStream(filepath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            var ext = Path.GetExtension(filepath).ToLowerInvariant();
            memory.Position = 0;

            return File(memory, GetMinetype()[ext], Path.GetFileName(filepath));
        }
        private Dictionary<string, string> GetMinetype()
        {
            return new Dictionary<string, string>
            {
                {".docx", "application/vnd.ms-word" },
                {".doc", "application/vnd.ms-word" },
            };
        }
    }
}

Jwt_Template/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("API", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Upload File", "FileUpload", "Account", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Generate Template", "Index", "FillDocx", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://templater.info">Template API</a></li>
                    @if (Session["UserName"] != null)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                @Session["UserName"].ToString() <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                <li>@Html.ActionLink("Upload", "FileUpload", "Account")</li>
                                <li>@Html.ActionLink("Generate Template", "Index", "FillDocx")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Logout", "LogOut", "Account")</li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>